on:
  workflow_dispatch:
  # push:
  schedule:
  - cron: "0 4 * * *"

name: update
jobs:
  update:
    name: update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Setup reprepro debian repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb https://packaging.gitlab.io/reprepro-multiple-versions noble main
          repo-name: reprepro-multiple-versions
          keys-asc: https://packaging.gitlab.io/reprepro-multiple-versions/gpg.key
          update: true
      - name: Install reprepro
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: apt-mirror apt-transport-https reprepro
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: test gpg key
        # unlocks gpg agent so reprepro stops bloody crashing
        run: echo "123" | gpg -s --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --clearsign
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Run fetcher
        run: cd fetcher && bun i --production && bun index.ts
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'automated: update packages'
          commit_options: '--no-verify --signoff'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
