on:
  workflow_dispatch:
  schedule:
  - cron: "0 4 * * *"

name: update
jobs:
  update:
    name: update packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Setup reprepro debian repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb https://packaging.gitlab.io/reprepro-multiple-versions noble main
          repo-name: reprepro-multiple-versions
          keys-asc: https://packaging.gitlab.io/reprepro-multiple-versions/gpg.key
          update: true
      - name: Install reprepro
        uses: awalsh128/cache-apt-pkgs-action@v1.5.3
        with:
          packages: apt-mirror apt-transport-https reprepro
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ""
          fingerprint: BFADC90DB92BB93CF7A4D4A383C0169F2CB4BF0A
      - run: cd fetcher && bun i --production && bun index.ts
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'automated: update packages'
          commit_options: '--no-verify --signoff'
